### ISSUE TITLE
Tests fail due to 404 not found on testing/asserts

### ISSUE THREAD

**Issue by ItsRauf** [denomod/deno_starter#3]
The following code causes tests to fail as `std@v1.0.0-rc1` does not exist, the most latest is `std@0.53.0` as of 05/26/2020

https://github.com/denomod/deno_starter/blob/b729440fc560419243f00e396cd740089b51e40e/mod_test.ts#L1

**Comment by ItsRauf** [comment]
forgot to include error log
```
Run deno test
Compile file:///home/runner/work/deno-id3/deno-id3/.deno.test.ts
Download https://deno.land/std@v1.0.0-rc1/testing/asserts.ts
error: Uncaught Error: Import 'https://deno.land/std@v1.0.0-rc1/testing/asserts.ts' failed: 404 Not Found
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:98:10)
    at async processImports ($deno$/compiler/imports.ts:117:23)
    at async processImports ($deno$/compiler/imports.ts:125:7)
    at async Object.processImports ($deno$/compiler/imports.ts:125:7)
    at async compile (file:///home/runner/work/deno/deno/cli/js/compiler.ts:144:31)
    at async tsCompilerOnMessage (file:///home/runner/work/deno/deno/cli/js/compiler.ts:359:22)
    at async workerMessageRecvCallback ($deno$/runtime_worker.ts:73:9)
##[error]Process completed with exit code 1.
```
